# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-09 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180709_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='platform_id',
            field=models.CharField(max_length=64),
        ),
    ]
